ALTER PROC BRUTE_FORCE_DETECTION
AS 

CREATE TABLE #LOG (LOGDATE DATETIME ,PROCESSINFO VARCHAR(100),TEXT VARCHAR(MAX))
INSERT INTO #LOG EXEC XP_READERRORLOG

DECLARE @IP AS VARCHAR(100)='192.168.1.5' 
DECLARE @COUNT AS INT
DECLARE @BEGDATE AS DATETIME
DECLARE @ENDDATE AS DATETIME
DECLARE @TEXT AS VARCHAR(1000)
DECLARE @MSG AS VARCHAR (MAX)

--VERÝLER GÝRÝLMEDEN MAÝL YOLLAMA VE TABLOYA KAYDETME
SELECT @COUNT=COUNT(*),@BEGDATE=MIN(LOGDATE),@ENDDATE=MAX(LOGDATE),@TEXT=TEXT FROM #LOG
WHERE TEXT LIKE 'login failed%' and LOGDATE >=DATEADD(MINUTE,-30,GETDATE())
GROUP BY TEXT
INSERT INTO AUDIT.DBO.BRUTE_FORCE_ATTACK ([COMPUTERIP], [DATE_], [BEGDATE], [ENDDATE], [COUNT])
VALUES (@IP,GETDATE(),@BEGDATE,@ENDDATE,@COUNT)

SELECT @COUNT,@BEGDATE,@ENDDATE,@TEXT

--MAÞLLERÝ KISA YOLDAN YOLLAMA
IF @COUNT>1
BEGIN
EXEC msdb.dbo.sp_send_dbmail  
    @profile_name = 'SQLMAIL',  
    @recipients = 'kursatsahin565@gmail.com',  
    @body = @MSG ,  
    @subject = 'Brute Force Attack Detected' ;  
END  


--VERÝLER GÝRÝLEREK MAÝL YOLLAMA
SET @MSG='Your system is under attack! A machine with IP ' 
SET @MSG=@MSG+@IP
SET @MSG=@MSG+' has tried '+CONVERT(VARCHAR,@COUNT)+' wrong password between '
SET @MSG=@MSG+CONVERT(VARCHAR,@BEGDATE,108)+' and '+ CONVERT(VARCHAR,@ENDDATE,108)
SELECT @MSG

DROP TABLE #LOG